version: '2'
# Service for SSP
services:
  # Postgresql container
  ssp-postgresql:
    image: docker.skidata.net/ssp-postgresql:0.3
  # build: ./postgres
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
  # RabbitMQ container
  ssp-rabbitmq:
    image: tutum/rabbitmq
    expose:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_PASS: admin
    restart: always
  # Discovery container
  ssp-discovery:
    image: docker.skidata.net/ssp-discovery:0.6.3-SNAPSHOT
    expose:
      - "8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Xmx512m -Xss256k"
    restart: always
  # Auth container
  ssp-auth:
    image: docker.skidata.net/ssp-auth:0.6.5-SNAPSHOT
    ports:
      - "9999"
    links:
      - ssp-discovery
      - ssp-rabbitmq
      - ssp-postgresql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      VIRTUAL_HOST: "*/auth, */auth/*"
    restart: always
  # Product container
  ssp-pim:
    image: docker.skidata.net/ssp-pim:0.6.3-SNAPSHOT
    expose:
      - "31020"
    links:
      - ssp-discovery
      - ssp-rabbitmq
      - ssp-postgresql
      - ssp-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure
  # Gateway container
  ssp-gateway:
    image: docker.skidata.net/ssp-gateway:0.6.4-SNAPSHOT
    ports:
      - "8080"
    links:
      - ssp-discovery
      - ssp-auth
      - ssp-pim
      - ssp-partner
      - ssp-notification
    environment:
      SPRING_PROFILES_ACTIVE: docker
      VIRTUAL_HOST: "*/*"
    restart: on-failure
  # Portal container
  ssp-portal:
    image: docker.skidata.net/ssp-portal:0.6.7-SNAPSHOT
    ports:
      - "10000"
    links:
      - ssp-discovery
      - ssp-gateway
      - ssp-postgresql
      - ssp-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SSP_HOSTNAME: "$SSP_HOSTNAME"
      VIRTUAL_HOST: "*/portal, */portal/*"  
    restart: on-failure      
  #Partner-Container
  ssp-partner:
     image: docker.skidata.net/ssp-partner:0.6.3-SNAPSHOT
     expose:
      - "31010"
     links:
        - ssp-discovery
        - ssp-postgresql
        - ssp-rabbitmq
        - ssp-auth
     environment:
          SPRING_PROFILES_ACTIVE: docker
     restart: on-failure 
  #Notification-Container
  ssp-notification:
     image: docker.skidata.net/ssp-notification:0.6.3-SNAPSHOT
     expose:
      - "30020"
     links:
        - ssp-discovery
        - ssp-rabbitmq
        - ssp-postgresql
        - ssp-auth
     environment:
          SPRING_PROFILES_ACTIVE: docker
     restart: on-failure
  #Vault-Container
  ssp-vault:
     image: docker.skidata.net/ssp-vault:0.6.3-SNAPSHOT
     expose:
      - "30010"
     links:
        - ssp-discovery
        - ssp-rabbitmq
        - ssp-auth
        - ssp-postgresql
     environment:
          SPRING_PROFILES_ACTIVE: docker
     restart: on-failure 
  #Dta-Adapter
  ssp-dta-adapter:
    image: docker.skidata.net/ssp-dta-adapter:0.6.3-SNAPSHOT
    expose:
      - "40010"
    links:
      - ssp-discovery
      - ssp-rabbitmq
      - ssp-postgresql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure
  #Admin Portal container
  ssp-vsm-admin:
    image: docker.skidata.net/ssp-vsm-admin:0.6.3-SNAPSHOT
    ports:
      - "20000"
    links:
      - ssp-discovery
      - ssp-gateway
      - ssp-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SSP_HOSTNAME: "$SSP_HOSTNAME"
      VIRTUAL_HOST: "*/ssp-vsm-admin, */ssp-vsm-admin/*"
    restart: on-failure
  # Order container
  ssp-order:
    image: docker.skidata.net/ssp-order:0.6.3-SNAPSHOT
    expose:
      - "32010"
    links:
      - ssp-discovery
      - ssp-rabbitmq
      - ssp-postgresql
      - ssp-auth
      - ssp-partner
      - ssp-pim
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure
  #VSM-Adapter
  ssp-vsm-adapter:
    image: docker.skidata.net/ssp-vsm-adapter:0.0.1-SNAPSHOT
    expose:
      - "40030"
    links:
      - ssp-discovery
      - ssp-rabbitmq
      - ssp-postgresql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure
  # HA Proxy 
  ssp-haproxy:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 8080:80
      - 8443:443
    links: 
      - ssp-gateway
      - ssp-auth  
      - ssp-portal
      - ssp-vsm-admin
    restart: always
# Persistent volumes for SSP
volumes:
    db_data: