version: '2'
# Service for SSP
services:
  # Postgresql container
  ssp-postgresql:
    image: swblr.skidata.net/ssp-postgresql:0.3
  # build: ./postgres
    mem_limit: 1024m
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
  # RabbitMQ container
  ssp-rabbitmq:
    image: tutum/rabbitmq
    mem_limit: 1024m
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_PASS: admin
    restart: always
  # Discovery container
  ssp-discovery:
    image: swblr.skidata.net/ssp-discovery:0.6.3-SNAPSHOT
    mem_limit: 1024m
    ports:
      - 8761:8761
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Xmx512m -Xss256k"
    restart: always
  # Auth container
  ssp-auth:
    image: swblr.skidata.net/ssp-auth:0.6.5-SNAPSHOT
    mem_limit: 1024m
    ports:
      - 9999:9999
    links:
      - ssp-discovery
      - ssp-rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
      VIRTUAL_HOST: "*/auth, */auth/*"
    restart: always
  # Product container
  ssp-pim:
    image: swblr.skidata.net/ssp-pim:0.6.3-SNAPSHOT
    mem_limit: 1024m
    ports:
      - 31020:31020
    links:
      - ssp-discovery
      - ssp-rabbitmq
      - ssp-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure
  # Gateway container
  ssp-gateway:
    image: swblr.skidata.net/ssp-gateway:0.6.4-SNAPSHOT
    mem_limit: 1024m
    ports:
      - 8080:8080
    links:
      - ssp-discovery
      - ssp-auth
      - ssp-pim
      - ssp-partner
      - ssp-notification
    environment:
      SPRING_PROFILES_ACTIVE: docker
      VIRTUAL_HOST: "*/*"
    restart: on-failure
  # Portal container
  ssp-portal:
    image: swblr.skidata.net/ssp-portal:0.6.4-SNAPSHOT
    mem_limit: 1024m
    ports:
      - 10000:10000
    links:
      - ssp-discovery
      - ssp-gateway
      - ssp-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SSP_HOSTNAME: "$SSP_HOSTNAME"
      VIRTUAL_HOST: "*/portal, */portal/*"  
    restart: on-failure      
  #Partner-Container
  ssp-partner:
     image: swblr.skidata.net/ssp-partner:0.6.3-SNAPSHOT
     mem_limit: 1024m
     ports:
      - 31010:31010
     links:
        - ssp-discovery
        - ssp-rabbitmq
        - ssp-auth
     environment:
          SPRING_PROFILES_ACTIVE: docker
     restart: on-failure 
  #Notification-Container
  ssp-notification:
     image: swblr.skidata.net/ssp-notification:0.6.3-SNAPSHOT
     mem_limit: 1024m
     ports:
      - 30020:30020
     links:
        - ssp-discovery
        - ssp-rabbitmq
        - ssp-auth
     environment:
          SPRING_PROFILES_ACTIVE: docker
     restart: on-failure
  #Vault-Container
  ssp-vault:
     image: swblr.skidata.net/ssp-vault:0.6.3-SNAPSHOT
     mem_limit: 1024m
     ports:
      - 30010:30010
     links:
        - ssp-discovery
        - ssp-rabbitmq
        - ssp-auth
        - ssp-postgresql
     environment:
          SPRING_PROFILES_ACTIVE: docker
     restart: on-failure 
  #Dta-Adapter
  ssp-dta-adapter:
    image: swblr.skidata.net/ssp-dta-adapter:0.6.3-SNAPSHOT
    mem_limit: 1024m
    ports:
      - 40010:40010
    links:
      - ssp-discovery
      - ssp-rabbitmq
      - ssp-postgresql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure
  #Admin Portal container
  ssp-vsm-admin:
    image: swblr.skidata.net/ssp-vsm-admin:0.6.3-SNAPSHOT
    mem_limit: 1024m
    ports:
      - 20000:20000
    links:
      - ssp-discovery
      - ssp-gateway
      - ssp-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SSP_HOSTNAME: "$SSP_HOSTNAME"
      VIRTUAL_HOST: "*/ssp-vsm-admin, */ssp-vsm-admin/*"
    restart: on-failure
  # Order container
  ssp-order:
    image: swblr.skidata.net/ssp-order:0.6.3-SNAPSHOT
    mem_limit: 1024m
    ports:
      - 32010:32010
    links:
      - ssp-discovery
      - ssp-rabbitmq
      - ssp-auth
      - ssp-partner
      - ssp-pim
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure
  #VSM-Adapter
  ssp-vsm-adapter:
    image: swblr.skidata.net/ssp-vsm-adapter:0.0.1-SNAPSHOT
    mem_limit: 1024m
    ports:
      - 40030:40030
    links:
      - ssp-discovery
      - ssp-rabbitmq
      - ssp-postgresql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure
  # HA Proxy 
  ssp-haproxy:
    image: dockercloud/haproxy
    mem_limit: 512m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 80:80
      - 443:443
    links: 
      - ssp-gateway
      - ssp-auth  
      - ssp-portal
      - ssp-vsm-admin
    restart: always
# Persistent volumes for SSP
volumes:
    db_data: